version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  measure_app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/home/node/server
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  database-data: